export const colorNames = [
	'black',
	'white',
	// 'slate',
	'gray',
	// 'zinc',
	// 'neutral',
	// 'stone',
	'red',
	'orange',
	'amber',
	'yellow',
	'lime',
	'green',
	// 'emerald',
	'teal',
	'cyan',
	// 'sky',
	'blue',
	'indigo',
	// 'violet',
	'purple',
	// 'fuchsia',
	'pink',
	'rose'
] as const

export const bgColors: BgColors = {
	black: 'bg-black',
	white: 'bg-white',
	// slate: "bg-slate-400",
	gray: 'bg-gray-400',
	// zinc: "bg-zinc-400",
	// neutral: "bg-neutral-400",
	// stone: "bg-stone-400",
	red: 'bg-red-400',
	orange: 'bg-orange-400',
	amber: 'bg-amber-400',
	yellow: 'bg-yellow-400',
	lime: 'bg-lime-400',
	green: 'bg-green-400',
	// emerald: "bg-emerald-400",
	teal: 'bg-teal-400',
	cyan: 'bg-cyan-400',
	// sky: "bg-sky-400",
	blue: 'bg-blue-400',
	indigo: 'bg-indigo-400',
	// violet: "bg-violet-400",
	purple: 'bg-purple-400',
	// fuchsia: "bg-fuchsia-400",
	pink: 'bg-pink-400',
	rose: 'bg-rose-400'
}

export const textColors: TextColors = {
	black: 'text-black',
	white: 'text-white',
	// slate: "text-slate-500",
	gray: 'text-gray-500',
	// zinc: "text-zinc-500",
	// neutral: "text-neutral-500",
	// stone: "text-stone-500",
	red: 'text-red-500',
	orange: 'text-orange-500',
	amber: 'text-amber-500',
	yellow: 'text-yellow-500',
	lime: 'text-lime-500',
	green: 'text-green-500',
	// emerald: "text-emerald-500",
	teal: 'text-teal-500',
	cyan: 'text-cyan-500',
	// sky: "text-sky-500",
	blue: 'text-blue-500',
	indigo: 'text-indigo-500',
	// violet: "text-violet-500",
	purple: 'text-purple-500',
	// fuchsia: "text-fuchsia-500",
	pink: 'text-pink-500',
	rose: 'text-rose-500'
}

export const borderColors: BorderColors = {
	black: 'border-black',
	white: 'border-white',
	// slate: "border-slate-500",
	gray: 'border-gray-500',
	// zinc: "border-zinc-500",
	// neutral: "border-neutral-500",
	// stone: "border-stone-500",
	red: 'border-red-500',
	orange: 'border-orange-500',
	amber: 'border-amber-500',
	yellow: 'border-yellow-500',
	lime: 'border-lime-500',
	green: 'border-green-500',
	// emerald: "border-emerald-500",
	teal: 'border-teal-500',
	cyan: 'border-cyan-500',
	// sky: "border-sky-500",
	blue: 'border-blue-500',
	indigo: 'border-indigo-500',
	// violet: "border-violet-500",
	purple: 'border-purple-500',
	// fuchsia: "border-fuchsia-500",
	pink: 'border-pink-500',
	rose: 'border-rose-500'
}

export const strokesColors: StrokeColors = {
	black: 'stroke-black',
	white: 'stroke-white',
	// slate: "stroke-slate-500",
	gray: 'stroke-gray-500',
	// zinc: "stroke-zinc-500",
	// neutral: "stroke-neutral-500",
	// stone: "stroke-stone-500",
	red: 'stroke-red-500',
	orange: 'stroke-orange-500',
	amber: 'stroke-amber-500',
	yellow: 'stroke-yellow-500',
	lime: 'stroke-lime-500',
	green: 'stroke-green-500',
	// emerald: "stroke-emerald-500",
	teal: 'stroke-teal-500',
	cyan: 'stroke-cyan-500',
	// sky: "stroke-sky-500",
	blue: 'stroke-blue-500',
	indigo: 'stroke-indigo-500',
	// violet: "stroke-violet-500",
	purple: 'stroke-purple-500',
	// fuchsia: "stroke-fuchsia-500",
	pink: 'stroke-pink-500',
	rose: 'stroke-rose-500'
}

export type BgColors = Record<Color, string>
export type TextColors = Record<Color, string>
export type BorderColors = Record<Color, string>
export type StrokeColors = Record<Color, string>
export type Color = (typeof colorNames)[number]
