import type { Metadata } from 'next'
import './globals.css'
import TheHeader from '@/components/header/TheHeader'
import TheFooter from '@/components/footer/TheFooter'
import localFont from 'next/font/local'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900'
})
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900'
})

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
			>
				<TheHeader />
				<main className="flex-grow">{children}</main>
				<TheFooter />
			</body>
		</html>
	)
}
