import AppProviders from '../_component/AppProviders'
import '../globals.css'
import { getMessages } from 'next-intl/server'
export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default async function RootLayout({ children, params: { locale } }) {
	const messages = await getMessages()

	return (
		<html lang={locale} suppressHydrationWarning>
			<body className={`antialiased`}>
				<AppProviders messages={messages} locale={locale}>
					{children}
				</AppProviders>
			</body>
		</html>
	)
}
