import localFont from 'next/font/local'
import './globals.css'
import NavBar from './_components/NavBar'
import { SessionProvider } from '@/app/_components/SessionProvider'
import { getServerSession } from 'next-auth'
import { data } from './_data/userData'
const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900'
})
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900'
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default async function RootLayout(props, pageProps) {
	const sesssion = await getServerSession()
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gray-200`}
			>
				<SessionProvider session={sesssion}>
					<NavBar />
					{props.children}
				</SessionProvider>
			</body>
		</html>
	)
}
